name: Release Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print checked code and check environments
        run: |
          ls -lah
          echo $(pwd)
          echo $(which cmake)
      - name: Run Cmake Configuration
        run: cmake -S . -B build 
      - name: Build MultTiming 
        run: cmake --build build --target MultTiming -j
        
